services:
  app:
      build: .
      container_name: app
      restart: always
      volumes:
        - ./:/usr/app/.
      working_dir: /usr/app/.
      ports:
        - "8000:8000"
      command:  bash -c 'python src/manage.py migrate && python src/manage.py runserver 0.0.0.0:8000'
      env_file:
        - .env
      depends_on:
        - cache
        - db
      networks:
        - app_network
      expose:
        - 8000

  cache:
      image: redis:latest
      container_name: cache
      restart: always
      networks:
        - app_network
      environment:
        - REDIS_PORT=${REDIS_PORT}
        - REDIS_HOST=${REDIS_HOST}

  db:
    image: postgres:latest
    container_name: db
    restart: always
    networks:
      - app_network
    ports:
      - 5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}


networks:
  app_network: