# Generated by Django 5.0.6 on 2024-05-09 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='avatar',
        ),
    ]
