# Generated by Django 5.0.6 on 2024-05-09 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_myuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='referred_by',
            field=models.CharField(default=None, null=True),
        ),
    ]
